### Llama 3.2 on Ollama
POST http://localhost:11434/api/chat

{
  "model": "llama3.2",
  "messages": [
    {
      "role": "user",
      "content": "why is the sky blue?"
    }
  ],
  "stream": false
}
