name: pipeline
on: pull_request

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
        dependencies: ['lowest', 'highest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Composer Validation
        run: composer validate --strict

      - name: Install PHP Dependencies
        run: composer install --no-scripts

      - name: Code Style PHP
        run: vendor/bin/php-cs-fixer fix --dry-run

      - name: Rector
        run: vendor/bin/rector

      - name: PHPStan
        run: vendor/bin/phpstan analyse

      - name: Tests
        run: vendor/bin/phpunit
